modulo estrutural price com as funcionalidades add, view e edit
Douglaxz/APP-Park pull request #3
Opened 2023-07-10 14:03 UTC by Douglaxz

Prezados, boa tarde

Seguem as mudanças neste pull request:
app view - remoção do logo da Vue
firebase.config - importação do modulo getFirestore
main.js - instalação do modulo price
criação das pastas e aquivos index.js (modules, api, store, router, view)
criado a view add - separando a inclusão de preços do list
alteração do modulo list - retirado a inclusão
alteração da About para Dashboard
HomeView - Alteração de rota da about para dashboard

2023-07-10 14:20 UTC, LuizFeller approved these changes

2023-07-10 17:59 UTC, abimaelneto commented on src/modules/price/store/index.js
> +  items: [],
poderia chamar items de prices, só para melhor significado do array

2023-07-10 18:00 UTC, abimaelneto commented on src/modules/price/views/Add.vue
> +  }
```suggestion
  if (!res) return;
  alert("Item da tabela de preços criado com sucesso");
  window.location.href = "/price";
  
```

2023-07-10 18:04 UTC, abimaelneto commented on src/modules/price/views/Add.vue
> +  }
```suggestion
  if (!res) return;
  alert("Item da tabela de preços criado com sucesso");
  window.location.href = "/price";
  
```

2023-07-10 18:07 UTC, abimaelneto requested changes
favor dar uma olhada nas mudanças sugeridas

2023-07-10 18:07 UTC, abimaelneto commented on src/modules/price/views/List.vue
> +async function handleCreatePrice() {
acho que essa função está sobrando

2023-07-10 18:17 UTC, abimaelneto reviewed
Achei legal que foi feito rapidamente um módulo inteiro. Nesse caso está ok para revisar, mas se for fazer mais completo no próximo módulo, facilita a revisão se quebrar em PRs menores.

2023-07-11 13:06 UTC, Douglaxz commented on src/modules/price/store/index.js
> +  items: [],
FInalizado, valeu!

2023-07-11 14:04 UTC, Douglaxz commented on src/modules/price/views/Add.vue
> +  }
perfeito, corrigido

2023-07-11 14:06 UTC, Douglaxz commented on src/modules/price/views/List.vue
> +async function handleCreatePrice() {
realmente esta sobrando a newTitle e  a função handleCreatePrice, que foi transferida pra add.vue

2023-07-11 18:57 UTC, abimaelneto approved these changes

2023-07-12 17:51 UTC, merged